"""Add currency table

Revision ID: 31b3b6f63a45
Revises: 
Create Date: 2024-02-22 11:30:22.487787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b3b6f63a45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(), nullable=True, comment='Currency name'),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=False, comment='Currency rate to USD'),
    sa.Column('code', sa.String(length=5), nullable=False, comment='Currency code'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update date'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
