name: FastAPI CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file:  Dockerfile
          push: true
          tags: ghcr.io/kairick/currency_convertor:latest

      - name: Checkout code
        uses: actions/checkout@v2
  test:
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/kairick/currency_convertor:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: database
          POSTGRES_PORT: 5432
          DIALECT: postgresql
          DRIVER: psycopg
        ports:
          - 8000:8000
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ruff linter
        run: |
          ruff check .

      - name: Run pytest with test database
        run: |
          python -m pytest --cov=. --cov-fail-under=80
